import type { NorrixConfig } from '@norrix/cli';

/**
 * Norrix CLI Configuration
 * Generated by norrix build command
 * 
 * For more options, see: https://norrix.net/docs/configuration
 */
export default {
  ios: {
    teamId: '984WS83CKT',
    distributionType: 'appstore',
    // App Store Connect API Key (for auto-provisioning)
    ascApiKeyId: 'Q5F446LJB5',
    ascIssuerId: '0f4bade0-5c2f-41a3-b19d-672606c3ac39',
    ascPrivateKeyPath: './keys/AuthKey_Q5F446LJB5.p8',
  },
  android: {
    keystorePath: './signing/release.keystore',
    keyAlias: 'prayerstreaks',
  },
  defaultConfiguration: 'release',
} satisfies NorrixConfig;
